version: '1.0'
services:
  - name: db
    type: postgres
    version: 9.6
    configuration: StandAlone
    ports:
      - 5432
    username: cachethq
    database: cachethq
    userPassword: null
    remoteAccess: false
    deployTo:
      - cachethq


  - name: cachethq
    type: docker
    image: cachethq/docker
    version: 2.3
    ports:
      - 8000
    remoteAccess: false
    env:
      DB_DRIVER: "pgsql"
      DB_HOST: "{{=service('db').getMasterAlias()}}"
      DB_DATABASE: "{{=service('db').get('database')}}"
      DB_USERNAME: "{{=service('db').get('username')}}"
      DB_PASSWORD: "{{=service('db').get('userPassword')}}"
      APP_KEY: "{{=randomString(32)}}"
    deployTo:
      - cachethq

  - name: web
    type: nginx
    version: 1.14
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: cachethq
    deployTo:
      - cachethq

hosts:
  - name: cachethq
    requirements:
      cores: 1
      memory: 1
